apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    chart: myapp-chart
    repoURL: https://worldofprasanna.github.io/helm-chart-repository
    targetRevision: 0.1.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
